apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MONGO_URL: # base64 for mongo url

# Command:- echo -n 'mongodb+srv://<username>:<password>@cluster0.1cygt.mongodb.net/devopsified-mern?retryWrites=true&w=majority' | base64
